export const dummyBooks = [
  {
    title: "The Lost City",
    author: "Alice Carter",
    genre: "Adventure",
    publishedYear: "2019",
    status: "Available",
  },
  {
    title: "Shadows of Tomorrow",
    author: "James Smith",
    genre: "Science Fiction",
    publishedYear: "2021",
    status: "Issued",
  },
  {
    title: "Whispers in the Wind",
    author: "Lara Johnson",
    genre: "Romance",
    publishedYear: "2020",
    status: "Available",
  },
  {
    title: "The Final Empire",
    author: "Brandon Sanderson",
    genre: "Fantasy",
    publishedYear: "2015",
    status: "Available",
  },
  {
    title: "Beyond the Horizon",
    author: "Mark Twain",
    genre: "Classic",
    publishedYear: "1884",
    status: "Issued",
  },
  {
    title: "Digital Fortress",
    author: "Dan Brown",
    genre: "Thriller",
    publishedYear: "1998",
    status: "Available",
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Help",
    publishedYear: "2018",
    status: "Available",
  },
  {
    title: "The Road",
    author: "Cormac McCarthy",
    genre: "Post-apocalyptic",
    publishedYear: "2006",
    status: "Issued",
  },
  {
    title: "Gone Girl",
    author: "Gillian Flynn",
    genre: "Mystery",
    publishedYear: "2012",
    status: "Available",
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    genre: "Non-fiction",
    publishedYear: "2011",
    status: "Issued",
  },
  {
    title: "Educated",
    author: "Tara Westover",
    genre: "Memoir",
    publishedYear: "2018",
    status: "Available",
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    genre: "History",
    publishedYear: "2014",
    status: "Available",
  },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genre: "Psychological Thriller",
    publishedYear: "2019",
    status: "Issued",
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    genre: "Self-Help",
    publishedYear: "2012",
    status: "Available",
  },
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    genre: "Science",
    publishedYear: "1988",
    status: "Issued",
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    genre: "Science Fiction",
    publishedYear: "1965",
    status: "Available",
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Classic",
    publishedYear: "1813",
    status: "Available",
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Fiction",
    publishedYear: "1988",
    status: "Issued",
  },
  {
    title: "The Martian",
    author: "Andy Weir",
    genre: "Science Fiction",
    publishedYear: "2011",
    status: "Available",
  },
  {
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    genre: "Mystery",
    publishedYear: "2015",
    status: "Issued",
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Classic",
    publishedYear: "1960",
    status: "Available",
  },
  {
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    publishedYear: "1949",
    status: "Available",
  },
  {
    title: "Becoming",
    author: "Michelle Obama",
    genre: "Biography",
    publishedYear: "2018",
    status: "Issued",
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    publishedYear: "1937",
    status: "Available",
  },
  {
    title: "Inferno",
    author: "Dan Brown",
    genre: "Thriller",
    publishedYear: "2013",
    status: "Available",
  },
];
